### ISSUE TITLE
A3 crashes with ASP loaded following SPOTREP#00099

### ISSUE THREAD

**Issue by mwpowellhtx** [dedmen/ArmaScriptProfiler#25]
Seems coincident to the [_SPOTREP#00099_](https://dev.arma3.com/post/spotrep-00099) update. Whatever changed there has had a precipitous effect on _ASP_.

Attaching the reports. Also my mod set; you could probably pare back a couple of them, but the issue seems contained whether _ASP_ is in the mix.

[ArmaReport_Log_20210609T152103_mwpowelllde.zip](https://github.com/dedmen/ArmaScriptProfiler/files/6625121/ArmaReport_Log_20210609T152103_mwpowelllde.zip)

[a3-kplib-base-debug-mods.zip](https://github.com/dedmen/ArmaScriptProfiler/files/6625131/a3-kplib-base-debug-mods.zip)

**Comment by mwpowellhtx** [comment]
Added `-sqfasm-no-sqfc` to my parameters file as a possible workaround. Did not fix it. This is as far as A3 got in the logs, then crashed again.

```
12:03:12 Intercept initialization part 1/3: 1
12:03:12 Intercept initialization part 2/3: true
12:03:12 Intercept Loading Plugin: SQF-Assembly
12:03:12 "Intercept: Load completed [SQF-Assembly]"
12:03:12 Intercept Loading Plugin: ArmaScriptProfiler
12:03:13 "Intercept: Load completed [ArmaScriptProfiler]"
```

**Comment by dedmen** [comment]
Fixed with https://github.com/dedmen/SQF-Assembly/commit/ebfe47aaffb48db6321cded4150a9cd2a66a7ed9
just waiting for update to be deployed

**Comment by mwpowellhtx** [comment]
@dedmen that was quick, noice, thank you.

**Comment by mwpowellhtx** [comment]
@dedmen Q: are we clear of the issue, has it been published yet. Thanks...

**Comment by mwpowellhtx** [comment]
@dedmen Any updates on the ETA? Let me know how I can help, even with an interim build. I could *_REALLY_* use an ASP interceptor right about now. Thank you!

**Comment by DerZade** [comment]
This is still present😭 

I even tried to manually update the SQF-Assembly DLL (I used the [CI build from commit `fdd8841`](https://github.com/dedmen/SQF-Assembly/actions/runs/1022100030)), but it didn't fix the crashes.

**Comment by mwpowellhtx** [comment]
Computer still down? What's the sitrep here please @dedmen.

I have a manually updated package seems to be working on my system with the updated binaries. But you know, I am not going to fork and publish a fresh if I do not have to. Or spoof your credential for that matter.

Up to you, friend.

Thank you.

**Comment by DerZade** [comment]
> I have a manually updated package seems to be working on my system with the updated binaries. [...]

@mwpowellhtx  What exactly did you update? Like I said I tried using `intercept/sqf-assembly_x64.dll` and `intercept/sqf-assembly_x64.pdb` from the SQF-Assembly repo, but it didn't work for me, even with just the profiler (+ dependencies) loaded.

**Comment by mwpowellhtx** [comment]
@DerZade Things are being held pretty closely to the chest. If the author is willing to expand the team, I may be willing to help.

**Comment by DerZade** [comment]
> @DerZade Things are being held pretty closely to the chest. If the author is willing to expand the team, I may be willing to help.

This is an open source project. If you have a fix for the issues just open a PR or am I getting something wrong here?

**Comment by mwpowellhtx** [comment]
> This is an open source project. If you have a fix for the issues just open a PR or am I getting something wrong here?

Even if I did, it would still go unpublished, AFAIK.

**Comment by dedmen** [comment]
> Computer still down? What's the sitrep here please

yes. Sitrep is my CPU is on the way to AMD for them to fix or replace it.
No ETA, probably 2 months minimum.
